#!/usr/bin/env python3

import argparse
import boto3
import pprint
import subprocess
from tabulate import tabulate

print("\nEC2-EZ-Connect\n")
pp = pprint.PrettyPrinter(indent=2)
ec2 = boto3.client('ec2')

active_instances = []
response = ec2.describe_instances(
    Filters = [
        {
            'Name': 'instance-state-name',
            'Values': [
                'running',
            ]
            }
        ]
    )

counter = 0
for r in response['Reservations']:
    for i in r['Instances']:
        instance_id = i['InstanceId']
        az = i['Placement']['AvailabilityZone']
        tags = i['Tags']
        for t in tags:
            if t["Key"] == "Name":
                name = t["Value"]
        try:
            ip = i['PrivateIpAddress']
        except:
            pass
        instance_details = {
            "id": counter,
            "name": name,
            "instance_id": instance_id,
            "az": az,
            "ip": ip
            }
        active_instances.append(instance_details)
        counter += 1
"""       
counter = 0
for instance in active_instances:
    print(counter, instance)
    counter += 1
"""
print(tabulate(active_instances, headers="keys"))
w = int(input("\n>> "))
instance = active_instances[w]
cmd = "aws ec2-instance-connect send-ssh-public-key --instance-id %s --instance-os-user %s --ssh-public-key file:///Users/ahynes/.ssh/id_rsa.pub --availability-zone %s && ssh %s@%s" % (instance['instance_id'],"root",instance['az'],"root",instance['ip'])
subprocess.run(cmd, shell=True)
